# Generated by Django 4.2.11 on 2024-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_playlist_contents_playlist_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
