# Generated by Django 4.2.11 on 2024-04-24 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_title_playlist_name_remove_playlist_contents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="spotify_id",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        # migrations.AddField(
        #     model_name="playlist",
        #     name="tracks",
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AlterField(
            model_name="playlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
