# Generated by Django 4.2.11 on 2024-04-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_playlist_spotify_id_remove_playlist_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
