# Generated by Django 4.2.11 on 2024-04-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_playlist_author_playlist_tracks"),
    ]

    operations = [
    ]
