# Generated by Django 4.2.11 on 2024-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_playlist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
