# Generated by Django 4.2.11 on 2024-04-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_playlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='id',
            new_name='playlist_id',
        ),
    ]
