# Generated by Django 4.2.11 on 2024-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_id_playlist_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='snapshot_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
