# Generated by Django 4.2.11 on 2024-05-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_playlist_snapshot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='tracks',
            new_name='number_of_tracks',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='snapshot_id',
        ),
        migrations.CreateModel(
            name='PlaylistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tracks', models.TextField(blank=True, null=True)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.playlist')),
            ],
        ),
    ]
