# Generated by Django 4.2.11 on 2024-05-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_playlistinstance_tracks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistinstance",
            name="tracks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
