# Generated by Django 4.2.11 on 2024-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_playlistinstance_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistinstance",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
