# Generated by Django 4.2.11 on 2024-05-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_playlist_current_snapshot_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistinstance",
            name="tracks",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
