# Generated by Django 4.2.11 on 2024-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_playlistinstance_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
