# Generated by Django 4.2.11 on 2024-05-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_user_spotify_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="spotify_id",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
